/**
 * Created by rroman681 on 5/15/17.
 */
/*
 Will populate this more as more actions become necessary
 */
const constant = {
    TOGGLE_TRADITIONAL: "TOGGLE_TRADITIONAL",
    TOGGLE_TESTING: "TOGGLE_TESTING",
    FETCH_ITEM: "FETCH_ITEM",
    RETURN_ITEM: "RETURN_ITEM",
    CANCEL_FETCH: "CANCEL_FETCH",
    CHANGE_ITEM: "CHANGE_ITEM",
    CLEAR_ITEM: "CLEAR_ITEM",
    CHANGE_LESSON: "CHANGE_LESSON",
    SUBMIT_GUESS: "SUBMIT_GUESS",
    VALIDATE_GUESS: "VALIDATE_GUESS",
    UPDATE_SEARCH_RESULT: "UPDATE_SEARCH_RESULT",
    UPDATE_FORM_FOCUS: "UPDATE_FORM_FOCUS",
    UPDATE_SEARCH_COLLECTION: "UPDATE_SEARCH_COLLECTION",
    UPDATE_SEARCH_SUCCESS: "UPDATE_SEARCH_SUCCESS"
};

export default constant;